spring.application.name=order-service

#Database Connections

spring.h2.console.enabled=true
spring.datasource.url= jdbc:h2:mem:test
spring.jpa.hibernate.ddl-auto= update

# server connections

server.port = 8083
